name: 'Checkout OIDN'
description: 'Composite action for checkout OIDN with submodules'
inputs:
  pat:
    description: 'Personal Access Token needed to clone OIDN & submodules (mkl-dnn & weights)'
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout OIDN source code with submodule WA - Windows
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: |
         git lfs install

         # Cleanup working directory - ALWAYS
         Remove-Item ${env:GITHUB_WORKSPACE}\* -Recurse -Force
         git clone https://${{ inputs.pat }}@github.com/${{ github.repository }} ${env:GITHUB_WORKSPACE}

         git config --global --add safe.directory ${env:GITHUB_WORKSPACE}
         # FIXME later https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286
         git checkout ${env:GITHUB_SHA}
         git submodule status mkl-dnn
         git submodule status weights

         $mkl_dnn_sha_raw = git submodule status mkl-dnn | ForEach-Object { $_.split(" ")[0] }
         $mkl_dnn_sha = $mkl_dnn_sha_raw -replace '[^a-zA-Z0-9]', ''
         echo $mkl_dnn_sha

         $weights_sha_raw = git submodule status weights | ForEach-Object { $_.split(" ")[0] }
         $weights_sha = $weights_sha_raw -replace '[^a-zA-Z0-9]', ''
         echo $weights_sha


         echo "### Direct injection!!!"
         # Inject new submodules repo
         git config --file=.gitmodules submodule.mkl-dnn.url https://${{ inputs.pat }}@github.com/${{ github.repository }}.mkl-dnn
         git config --file=.gitmodules submodule.weights.url https://${{ inputs.pat }}@github.com/${{ github.repository }}.weights

         echo "### Update recursive"
         git submodule update --init --recursive --remote

         echo "### checkout submodules"

         # Bring back origin submodules commit sha
         cd ${env:GITHUB_WORKSPACE}\mkl-dnn
         git checkout $mkl_dnn_sha
         git show -s --format=%H

         cd ${env:GITHUB_WORKSPACE}\weights
         git checkout $weights_sha
         git show -s --format=%H

      - name: Checkout OIDN source code with submodule WA - Non-Windows
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: |
         git lfs install

         # Cleanup working directory - ALWAYS
         ls -A $GITHUB_WORKSPACE | xargs rm -rf
         git clone https://${{ inputs.pat }}@github.com/${{ github.repository }} $GITHUB_WORKSPACE

         git config --global --add safe.directory $GITHUB_WORKSPACE
         # FIXME later https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286
         git checkout $GITHUB_SHA

         # For debug info
         mkl_dnn_sha=`git submodule status mkl-dnn | cut -d' ' -f1 | tr -cd '[:alnum:]'`
         weights_sha=`git submodule status weights | cut -d' ' -f1 | tr -cd '[:alnum:]'`

         echo "### Direct injection!!!"
         # Inject new submodules repo
         git config --file=.gitmodules submodule.mkl-dnn.url https://${{ inputs.pat }}@github.com/${{ github.repository }}.mkl-dnn
         git config --file=.gitmodules submodule.weights.url https://${{ inputs.pat }}@github.com/${{ github.repository }}.weights

         echo "### Update recursive"
         git submodule update --init --recursive --remote

         echo "### checkout submodules"

         # Bring back origin submodules commit sha
         cd $GITHUB_WORKSPACE/mkl-dnn
         git checkout $mkl_dnn_sha
         git show -s --format=%H

         cd $GITHUB_WORKSPACE/weights
         git checkout $weights_sha
         git show -s --format=%H

