on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
      runs-on:
        required: true
        type: string
      architecture:
        required: false
        type: string
        default: x86

jobs:
  build-macos:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    env:
      SHELL: ${{ inputs.shell }}
    steps:
      # We need to checkout code first to get access to repo actions
      # used in next step.
      - uses: actions/checkout@v3
      # Custom action to WA submodules problem with OIDN
      - name: Checkout OIDN src code with submodules
        uses: ./.github/actions/checkout
        with:
          pat: ${{ secrets.PAT_TOKEN }}

      - name: Execute x86 bash command
        if: ${{ inputs.architecture == 'x86' }}
        shell: bash
        run: ${{ inputs.cmd }}

      - name: Execute arm bash command
        if: ${{ inputs.architecture == 'arm' }}
        shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
        run: ${{ inputs.cmd }}

      - name: Compress artifact files
        if: ${{ inputs.artifact-name }}
        run: |
         tar -zcvf build.tar.gz ./build
         tar -zcvf deps.tar.gz ./deps

      - name: Upload artifact
        if: ${{ inputs.artifact-name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            build.tar.gz
            deps.tar.gz