on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: '[ "snyk" ]'

jobs:
  snyk-scan:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    env: 
      CI_TOOLS_PATH: /NAS/tools/ci_tools/ci_tools-0.3.1

    defaults:
      run:
        shell: bash
    steps:
      # We need to checkout code first to get access to repo actions
      # used in next step.
      - uses: actions/checkout@v3
      # Custom action to WA submodules problem with OIDN
      - name: Checkout OIDN src code with submodules
        uses: ./.github/actions/checkout
        with:
          pat: ${{ secrets.PAT_TOKEN }}

      - name: Scan Snyk
        shell: bash
        run: |
         $CI_TOOLS_PATH/bin/snyk.sh
