on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      cmd:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      runs-on:
        required: true
        type: string

jobs:
  test-linux:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container:
      image: amr-registry.caas.intel.com/renderkit/${{ inputs.docker-image }}
      options: --user root
      # Need NAS to access baseline images
      volumes:
        - /NAS:/NAS

    env:
      OIDN_TRAINING_DIR_LINUX: /NAS/oidn
      # SDE for emulate SSE4 instruction set
      OIDN_SDE_DIR_LINUX: /NAS/packages/apps/sde/lin

    steps:
      # We need to checkout code first to get access to repo actions
      # used in next step.
      - uses: actions/checkout@v3
      # Custom action to WA submodules problem with OIDN
      - name: Checkout OIDN src code with submodules
        uses: ./.github/actions/checkout
        with:
          pat: ${{ secrets.PAT_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}

      - name: Uncompress artifact files
        run: |
         tar -xvf build.tar.gz
         tar -xvf deps.tar.gz

      - name: Execute test command
        shell: bash
        run: ${{ inputs.cmd }}