on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      shell:
        required: false
        type: string
        default: bash
      architecture:
        required: false
        type: string
        default: x86

jobs:
  test-macos:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    env:
      OIDN_TRAINING_DIR_MACOS: /NAS/oidn

    steps:
      # We need to checkout code first to get access to repo actions
      # used in next step.
      - uses: actions/checkout@v3
      # Custom action to WA submodules problem with OIDN
      - name: Checkout OIDN src code with submodules
        uses: ./.github/actions/checkout
        with:
          pat: ${{ secrets.PAT_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}

      - name: Uncompress artifact files
        run: |
         tar -xvf build.tar.gz
         tar -xvf deps.tar.gz

      - name: Execute x86 bash command
        if: ${{ inputs.architecture == 'x86' }}
        shell: bash
        run: ${{ inputs.cmd }}

      - name: Execute arm bash command
        if: ${{ inputs.architecture == 'arm' }}
        shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
        run: ${{ inputs.cmd }}